### ISSUE TITLE
python3.9  TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Zz928** [hansalemaos/adbblitz#1]
python3.9  Using sample code

Traceback (most recent call last):
  File "D:\Program Files (x86)\Python3.9\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files (x86)\Python3.9\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "g:\AutoControl\scrcpy2\scrcpy2.py", line 364, in <module>
    from adbblitz import AdbShotUSB, AdbShotTCP
  File "D:\Program Files (x86)\Python3.9\lib\site-packages\adbblitz\__init__.py", line 10, in <module>
    from subprocesskiller import kill_process_children_parents, kill_pid, kill_subprocs  
  File "D:\Program Files (x86)\Python3.9\lib\site-packages\subprocesskiller\__init__.py", line 260, in <module>
    pid: int, max_parent_exe: str | None = None, dontkill: tuple = ()
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by hansalemaos** [comment]
Thanks for your post, either you update to 3.10 or you delete the those type hints in the source code. Type hints like data: list|tuple = (1,2,3) are only supported from 3.10 onwards.
